// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhachSan.Models;

namespace QuanLyKhachSan.Migrations
{
    [DbContext(typeof(QuanLyKhachSanContext))]
    [Migration("20230728112412_Test6")]
    partial class Test6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuanLyKhachSan.Models.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("MaChucVu")
                        .HasName("PK__ChucVu__D463953333E1199E");

                    b.ToTable("ChucVu");

                    b.HasData(
                        new
                        {
                            MaChucVu = 1,
                            TenChucVu = "Quan Ly"
                        },
                        new
                        {
                            MaChucVu = 2,
                            TenChucVu = "Le Tan"
                        },
                        new
                        {
                            MaChucVu = 3,
                            TenChucVu = "Thu Ngan"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DatPhong", b =>
                {
                    b.Property<int>("MaDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int>("SoNgayThue")
                        .HasColumnType("int");

                    b.Property<int>("ThanhTien")
                        .HasColumnType("int");

                    b.HasKey("MaDatPhong")
                        .HasName("PK__DatPhong__6344ADEABD7ACFA4");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("DatPhong");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.HasKey("MaKhachHang")
                        .HasName("PK__KhachHan__88D2F0E50D94392D");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("MaLoaiPhong")
                        .HasName("PK__LoaiPhon__230212173274457F");

                    b.ToTable("LoaiPhong");

                    b.HasData(
                        new
                        {
                            MaLoaiPhong = 1,
                            DonGia = 0,
                            TenLoaiPhong = "VIP"
                        },
                        new
                        {
                            MaLoaiPhong = 2,
                            DonGia = 0,
                            TenLoaiPhong = "Binh Thuong"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NhanVien__77B2CA4742399806");

                    b.HasIndex("MaChucVu");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaTinhTrang")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhong")
                        .HasName("PK__Phong__20BD5E5BCC8A63C0");

                    b.HasIndex("MaLoaiPhong");

                    b.HasIndex("MaTinhTrang");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.TinhTrangPhong", b =>
                {
                    b.Property<int>("MaTinhTrang")
                        .HasColumnType("int");

                    b.Property<string>("TenTinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("MaTinhTrang")
                        .HasName("PK__TinhTran__89F8F669AEA3EA50");

                    b.ToTable("TinhTrangPhong");

                    b.HasData(
                        new
                        {
                            MaTinhTrang = 1,
                            TenTinhTrang = "Trong"
                        },
                        new
                        {
                            MaTinhTrang = 2,
                            TenTinhTrang = "Da Dat"
                        },
                        new
                        {
                            MaTinhTrang = 3,
                            TenTinhTrang = "Dang Sua Chua"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.TrangThaiDat", b =>
                {
                    b.Property<int>("MaTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("MaTrangThai")
                        .HasName("PK__TrangTha__AADE413819F5FC56");

                    b.ToTable("TrangThaiDat");

                    b.HasData(
                        new
                        {
                            MaTrangThai = 1,
                            TenTrangThai = "Da Thanh Toan"
                        },
                        new
                        {
                            MaTrangThai = 2,
                            TenTrangThai = "Chua Thanh Toan"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DatPhong", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__DatPhong__MaKhac__47DBAE45")
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__DatPhong__MaNhan__49C3F6B7")
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.Phong", "MaPhongNavigation")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK__DatPhong__MaPhon__48CFD27E")
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.TrangThaiDat", "MaTrangThaiNavigation")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaTrangThai")
                        .HasConstraintName("FK__DatPhong__MaTran__4AB81AF0")
                        .IsRequired();

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaPhongNavigation");

                    b.Navigation("MaTrangThaiNavigation");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.NhanVien", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.ChucVu", "MaChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .HasConstraintName("FK__NhanVien__MaChuc__398D8EEE")
                        .IsRequired();

                    b.Navigation("MaChucVuNavigation");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Phong", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.LoaiPhong", "MaLoaiPhongNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaLoaiPhong")
                        .HasConstraintName("FK__Phong__MaLoaiPho__4222D4EF")
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.TinhTrangPhong", "MaTinhTrangNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaTinhTrang")
                        .HasConstraintName("FK__Phong__MaTinhTra__4316F928")
                        .IsRequired();

                    b.Navigation("MaLoaiPhongNavigation");

                    b.Navigation("MaTinhTrangNavigation");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.KhachHang", b =>
                {
                    b.Navigation("DatPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.NhanVien", b =>
                {
                    b.Navigation("DatPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Phong", b =>
                {
                    b.Navigation("DatPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.TinhTrangPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.TrangThaiDat", b =>
                {
                    b.Navigation("DatPhongs");
                });
#pragma warning restore 612, 618
        }
    }
}
